// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

  // Aquí se inicializa Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksLMMww0xgjLNUwcRoxYoDAdmmMeS58E',
    appId: '1:762241439258:web:8f059b1cca575512aa63a3',
    messagingSenderId: '762241439258',
    projectId: 'notasonoda',
    authDomain: 'notasonoda.firebaseapp.com',
    storageBucket: 'notasonoda.firebasestorage.app',
    measurementId: 'G-XSBMQRZ3ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXF9YYZBGZOkoPz-mHQffoy_RobWXsef4',
    appId: '1:762241439258:android:99846b6e13f1ecdcaa63a3',
    messagingSenderId: '762241439258',
    projectId: 'notasonoda',
    storageBucket: 'notasonoda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJgJGL6rInpOHR76YkQwbXw0PVfutEF0',
    appId: '1:762241439258:ios:ce655214cd33cd4eaa63a3',
    messagingSenderId: '762241439258',
    projectId: 'notasonoda',
    storageBucket: 'notasonoda.firebasestorage.app',
    iosBundleId: 'com.example.notaSonora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqJgJGL6rInpOHR76YkQwbXw0PVfutEF0',
    appId: '1:762241439258:ios:ce655214cd33cd4eaa63a3',
    messagingSenderId: '762241439258',
    projectId: 'notasonoda',
    storageBucket: 'notasonoda.firebasestorage.app',
    iosBundleId: 'com.example.notaSonora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksLMMww0xgjLNUwcRoxYoDAdmmMeS58E',
    appId: '1:762241439258:web:86ff659a0be213fcaa63a3',
    messagingSenderId: '762241439258',
    projectId: 'notasonoda',
    authDomain: 'notasonoda.firebaseapp.com',
    storageBucket: 'notasonoda.firebasestorage.app',
    measurementId: 'G-3DQ222KHZ0',
  );
}
